apiVersion: apps/v1
kind: Deployment
metadata:
  name: RecruitProcess
  labels:
    app: RecruitProcess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RecruitProcess
  template:
    metadata:
      labels:
        app: RecruitProcess
    spec:
      containers:
        - name: RecruitProcess
          image: username/RecruitProcess:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5