server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://localhost:8081
          predicates:
            - Path=/users/** 
        - id: Recruit
          uri: http://localhost:8082
          predicates:
            - Path=/recruits/** 
        - id: App
          uri: http://localhost:8083
          predicates:
            - Path=/apps/** 
        - id: RecruitProcess
          uri: http://localhost:8084
          predicates:
            - Path=/recruitProcesses/** 
        - id: RecruitHistory
          uri: http://localhost:8085
          predicates:
            - Path= /recruitProcessViews/**
        - id: Notice
          uri: http://localhost:8086
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://User:8080
          predicates:
            - Path=/users/** 
        - id: Recruit
          uri: http://Recruit:8080
          predicates:
            - Path=/recruits/** 
        - id: App
          uri: http://App:8080
          predicates:
            - Path=/apps/** 
        - id: RecruitProcess
          uri: http://RecruitProcess:8080
          predicates:
            - Path=/recruitProcesses/** 
        - id: RecruitHistory
          uri: http://RecruitHistory:8080
          predicates:
            - Path= /recruitProcessViews/**
        - id: Notice
          uri: http://Notice:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
